CREATE TABLE "ATTEMPT_STATE_HISTORY" (
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
"CHANGE_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"PROCESSING_STATE" TEXT NOT NULL,
"DATA_STATE" TEXT NOT NULL,
"HOME_ARCHIVE_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
"ON_TAPE_ARCHIVE" TEXT DEFAULT 'N' NOT NULL,
"ON_SPINNING_ARCHIVE" TEXT DEFAULT 'N' NOT NULL,
"DB_OBJECT_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
"DB_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
"USER_CHANGED_BY" TEXT DEFAULT 'USER' NOT NULL,
PRIMARY KEY ("PFW_ATTEMPT_ID", "CHANGE_DATE"));
