CREATE TABLE "ATTEMPT_STATE" (
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
"PROCESSING_STATE" TEXT DEFAULT 'NEW' NOT NULL,
"DATA_STATE" TEXT DEFAULT 'NEW' NOT NULL,
"HOME_ARCHIVE_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
"ON_TAPE_ARCHIVE" TEXT DEFAULT 'N' NOT NULL,
"ON_SPINNING_ARCHIVE" TEXT DEFAULT 'N' NOT NULL,
"DB_OBJECT_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
"DB_STATE" TEXT DEFAULT 'ORIG' NOT NULL,
PRIMARY KEY ("PFW_ATTEMPT_ID"));
