CREATE TABLE "CATALOG" (
"FILENAME" TEXT NOT NULL,
"FILETYPE" TEXT NOT NULL,
"BAND" TEXT,
"TILENAME" TEXT,
"CCDNUM" INTEGER,
"OBJECTS" INTEGER,
"EXPNUM" INTEGER,
"NITE" TEXT,
"CAMSYM" TEXT,
"FIELD" TEXT,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
PRIMARY KEY ("FILENAME"));
