CREATE TABLE "CATALOG" (
"FILENAME" TEXT NOT NULL,
"FILETYPE" TEXT NOT NULL,
"BAND" TEXT,
"TILENAME" TEXT,
"CCDNUM" INTEGER,
"OBJECTS" INTEGER,
"EXPNUM" INTEGER,
"NITE" TEXT,
"CAMSYM" TEXT,
"FIELD" TEXT,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
PRIMARY KEY ("FILENAME"));

INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_det_cat.fits', 'coadd_det_cat', NULL, 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_g_cat.fits', 'coadd_cat', 'g', 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_r_cat.fits', 'coadd_cat', 'r', 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_i_cat.fits', 'coadd_cat', 'i', 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_z_cat.fits', 'coadd_cat', 'z', 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
INSERT INTO CATALOG ('FILENAME','FILETYPE','BAND','TILENAME','CCDNUM','OBJECTS','EXPNUM','NITE','CAMSYM','FIELD','PFW_ATTEMPT_ID') VALUES ('DES0445-4957_r4969p01_Y_cat.fits', 'coadd_cat', 'Y', 'THETILE',NULL, 73298, NULL, NULL, 'D', NULL, 512);
