CREATE TABLE "CCDGON" (
    "CCDGON_NUMBER" INTEGER NOT NULL,
    "PFW_ATTEMPT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "BAND" TEXT NOT NULL,
    "RED_IMAGE_FILENAME" TEXT NOT NULL,
    "COADD_FILENAME" TEXT NOT NULL,
    "CCD_AMP" TEXT NOT NULL,
    "INVERSE_VARIANCE_WEIGHT" FLOAT,
    PRIMARY KEY ("CCDGON_NUMBER"));
