CREATE TABLE "COADD_OBJECT_HPIX" (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "HPIX_32" INTEGER NOT NULL,
    "HPIX_64" INTEGER NOT NULL,
    "HPIX_1024" INTEGER NOT NULL,
    "HPIX_4096" INTEGER NOT NULL,
    "HPIX_16384" INTEGER NOT NULL);
