CREATE TABLE "COADD_OBJECT_MOLYGON" (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "BAND" TEXT NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "PFW_ATTEMPT_ID" INTEGER NOT NULL,
    "MOLY_NUMBER" INTEGER,
    "MANGLE_FLAG" INTEGER,
    PRIMARY KEY ("COADD_OBJECT_ID", "FILENAME", "BAND"));
