CREATE TABLE "COADD_OBJECT_TEST"  (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "OBJECT_NUMBER" INTEGER NOT NULL,
    "PARENT_NUMBER" INTEGER,
    "BAND" TEXT NOT NULL,
    "TILENAME" TEXT NOT NULL,
    "PFW_ATTEMPT_ID" INTEGER NOT NULL
    );

CREATE VIEW "COADD_OBJECT_TEST2"
AS
SELECT
coadd_object_id as id,
filename, object_number,
parent_number,
band, tilename, pfw_attempt_id
from COADD_OBJECT_TEST;
