CREATE TABLE "COADD_OBJECT_TEST"  (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "OBJECT_NUMBER" INTEGER NOT NULL,
    "PARENT_NUMBER" INTEGER,
    "BAND" TEXT NOT NULL,
    "TILENAME" TEXT NOT NULL,
    "PFW_ATTEMPT_ID" INTEGER NOT NULL
    );

