CREATE TABLE "COMPRESS_TASK" (
"TASK_ID" INTEGER NOT NULL,
"NAME" TEXT NOT NULL,
"VERSION" TEXT NOT NULL,
"CMDARGS" TEXT,
"NUM_FAILED" INTEGER,
"NUM_REQUESTED" INTEGER,
"TOT_BYTES_AFTER" INTEGER,
"TOT_BYTES_BEFORE" INTEGER,
PRIMARY KEY ("TASK_ID"));
