CREATE TABLE "DESFILE" (
"ID" INTEGER NOT NULL,
"PFW_ATTEMPT_ID" INTEGER,
"WGB_TASK_ID" INTEGER NOT NULL,
"FILETYPE" TEXT NOT NULL,
"FILENAME" TEXT NOT NULL,
"COMPRESSION" TEXT,
"FILESIZE" INTEGER,
"MD5SUM" TEXT,
"USER_CREATED_BY" TEXT DEFAULT 'USER' NOT NULL,
"MODULE_CREATED_BY" TEXT DEFAULT 'USER' NOT NULL,
"CREATED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
PRIMARY KEY ("ID"));

