CREATE TABLE "FILE_REGISTRATION" (
"PROV_MSG" TEXT NOT NULL,
"CREATED_DATE" TIMESTAMP (6) DEFAULT 1234567890.,
"USER_CREATED_BY" TEXT DEFAULT 'USER',
"MODULE_CREATED_BY" TEXT DEFAULT 'USER',
"TASK_ID" INTEGER NOT NULL
);
