CREATE TABLE "MISCFILE" (
"FILENAME" TEXT NOT NULL,
"FILETYPE" TEXT NOT NULL,
"PFW_ATTEMPT_ID" INTEGER,
"CAMSYM" TEXT,
"BAND" TEXT,
"EXPNUM" INTEGER,
"CCDNUM" INTEGER,
"NITE" TEXT,
"FIELD" TEXT,
"TILENAME" TEXT,
PRIMARY KEY ("FILENAME"));


