CREATE TABLE "OPS_MESSAGE_FILTER" (
"EXECNAME" TEXT DEFAULT 'global' NOT NULL,
"USED" TEXT DEFAULT 'y' NOT NULL,
"REPLACE_PATTERN" TEXT NOT NULL,
"WITH_PATTERN" TEXT,
"LAST_CHANGED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"LAST_CHANGED_USER" TEXT DEFAULT 'USER' NOT NULL
);
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('scamp','y','chr(27)',NULL,1531507675.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('sex','y','chr(27)',NULL,1531507675.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('sex','y','[1A',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('sex','y','\x1b',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('sex','y','[1M',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('sex','y','[7m',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('scamp','y','[1A',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('scamp','y','\x1b',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('scamp','y','[1M',NULL,1498584479.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_FILTER (EXECNAME,USED,REPLACE_PATTERN,WITH_PATTERN,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES ('scamp','y','[7m',NULL,1498584479.0,'FRIEDEL');
