CREATE TABLE "OPS_METADATA" (
"FILE_HEADER_NAME" TEXT NOT NULL,
"COLUMN_NAME" TEXT NOT NULL,
"DESCRIPTION" TEXT,
"POSITION" INTEGER NOT NULL,
"DATA_TYPE" TEXT,
"DATA_LENGTH" INTEGER,
"DATA_PRECISION" INTEGER,
"SOURCE" TEXT,
"DATA_SCALE" INTEGER,
PRIMARY KEY ("FILE_HEADER_NAME", "POSITION"));
