CREATE TABLE "OPS_DATAFILE_METADATA" (
"FILETYPE" TEXT NOT NULL,
"ATTRIBUTE_NAME" TEXT NOT NULL,
"POSITION" INTEGER DEFAULT 0 NOT NULL,
"COLUMN_NAME" TEXT NOT NULL,
"DATAFILE_DATATYPE" TEXT NOT NULL,
"CURRENT_FLAG" INTEGER DEFAULT 1 NOT NULL,
"MODIFIED_DATE" DATE DEFAULT 1234567890. NOT NULL,
"DERIVED" TEXT,
"HDU" TEXT,
"DATA_FORMAT" TEXT,
PRIMARY KEY ("FILETYPE", "ATTRIBUTE_NAME", "POSITION"));
