CREATE TABLE "OPS_MESSAGE_IGNORE" (
"PATTERN" TEXT NOT NULL,
"USED" TEXT DEFAULT 'y' NOT NULL,
"EXECNAME" TEXT DEFAULT 'global' NOT NULL,
"LAST_CHANGED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"LAST_CHANGED_USER" TEXT DEFAULT 'USER' NOT NULL
);
