CREATE TABLE "OPS_DATAFILE_TABLE" (
"FILETYPE" TEXT NOT NULL,
"TABLE_NAME" TEXT NOT NULL,
"DESCRIPTION" TEXT,
PRIMARY KEY ("FILETYPE"));
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_extinct_ebv','COADD_OBJECT_EXTINCTION',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_extinct_band','COADD_OBJECT_EXTINCTION_BAND',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_hpix','COADD_OBJECT_HPIX',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_satstar','SATSTAR',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_streak','STREAK',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_cat','coadd_object','objects from the coadd catalog');
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('compare_dflat_binned_fp','FLAT_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('xml_scamp','SCAMP_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('xml_psfex','PSF_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('psmfit','PSMFIT',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_finalcut','SE_OBJECT',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('snxml_psfex','PSF_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('snxml_scamp','SCAMP_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('skyfit_binned_fp','SKYFIT_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_xml_psfex','PSF_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_trailbox','BLEEDTRAIL',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_xml_scamp','COADD_ASTROM_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_xml_scamp_2','COADD_EXPOSURE_ASTROM_QA',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_wavg','WAVG',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('coadd_wavg_oclink','WAVG_OCLINK',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('mangle_csv_ccdgon','CCDGON',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('mangle_csv_molygon','MOLYGON',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('mangle_csv_molyccd','MOLYGON_CCDGON',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('mangle_csv_cobjmoly','COADD_OBJECT_MOLYGON',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('red_hpix','SE_OBJECT_HPIX',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_firstcut','SE_OBJECT',NULL);
INSERT INTO OPS_DATAFILE_TABLE (FILETYPE,TABLE_NAME,DESCRIPTION) VALUES ('cat_hstreak','STREAK',NULL);
