CREATE TABLE "OPS_MESSAGE_FILTER" (
"EXECNAME" TEXT DEFAULT 'global' NOT NULL,
"USED" TEXT DEFAULT 'y' NOT NULL,
"REPLACE_PATTERN" TEXT NOT NULL,
"WITH_PATTERN" TEXT,
"LAST_CHANGED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"LAST_CHANGED_USER" TEXT DEFAULT 'USER' NOT NULL
);
