CREATE TABLE "OPS_MESSAGE_PATTERN" (
"ID" INTEGER NOT NULL,
"LVL" INTEGER DEFAULT 3 NOT NULL,
"PRIORITY" INTEGER NOT NULL,
"EXECNAME" TEXT DEFAULT 'global' NOT NULL,
"USED" TEXT DEFAULT 'y' NOT NULL,
"NUMBER_OF_LINES" INTEGER DEFAULT 1 NOT NULL,
"PATTERN" TEXT NOT NULL,
"ONLY_MATCHED" TEXT DEFAULT 'N' NOT NULL,
"LAST_CHANGED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"LAST_CHANGED_USER" TEXT DEFAULT 'USER' NOT NULL,
PRIMARY KEY ("ID"));
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (21,2,999,'global','n',1,'PFW Messages','N',1498574990.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (22,1,1,'global','n',1,'User Defined','N',1498574997.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (23,1,810,'global','y',1,'command not found','N',1498575009.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (24,1,805,'global','y',1,'ORA-','N',1498575009.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (25,3,800,'genquerydb.py','y',1,'sql =','N',1498575010.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (26,1,325,'global','y',1,'Unable to match','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (27,1,320,'global','y',1,'No objects','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (28,1,315,'global','y',1,'No sources','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (29,1,310,'global','y',1,'No input matches','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (30,1,305,'global','y',1,'Unable to measure','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (31,1,300,'global','y',1,'All matches rejected','N',1498575023.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (32,3,845,'global','y',1,'WARN:','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (33,3,840,'global','y',1,'Warning','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (34,1,835,'global','y',1,'error','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (35,3,830,'global','y',1,'RuntimeWarning:','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (36,1,825,'global','y',1,'RuntimeError:','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (37,1,820,'global','y',1,'InvalidParameterError:','n',1498672867.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (38,1,815,'global','y',1,'Traceback','n',1498675539.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (0,2,998,'global','n',1,'Manual entry','n',1535652131.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (40,1,102,'global','y',1,'curl exitcode','n',1538058365.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (41,2,103,'global','y',1,'Could not connect to database','N',1538576761.0,'FRIEDEL');
INSERT INTO OPS_MESSAGE_PATTERN (ID,LVL,PRIORITY,EXECNAME,USED,NUMBER_OF_LINES,PATTERN,ONLY_MATCHED,LAST_CHANGED_DATE,LAST_CHANGED_USER) VALUES (39,1,100,'global','y',1,'no space left','n',1532629149.0,'FRIEDEL');
