CREATE TABLE "OPS_FILETYPE" (
"FILETYPE" TEXT NOT NULL,
"METADATA_TABLE" TEXT,
"DESCRIPTION" TEXT,
"FILETYPE_MGMT" TEXT,
PRIMARY KEY ("FILETYPE"));
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_hpix','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_cat_bpz','MISCFILE','Cat created from BPZ code','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_cat_bpz_color','MISCFILE','Color cat created as input for BPZ code','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_mof','MISCFILE','Fits created for MOF step','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('qa_immask','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_hstreak','CATALOG',NULL,'filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_bkg_hmmask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_hmmask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('qa_psfex','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_shear_chunk','MISCFILE','shear output from ngmix','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('list','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snxml_swarp','MISCFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_xtalk','DESFILE','crosstalk config file','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('text','DESFILE','generic filetype for an otherwise unclassified text file','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('png','MISCFILE','PNG files created from codes in qatoolkit','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_segmap','MISCFILE','Segmentation map created in create-finalcut-catalog','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snwgt_red','DESFILE','Weight hdu of image','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snhead_scamp','MISCFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snqa_scamp','MISCFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snxml_scamp','MISCFILE','SN','filemgmt.ftmgmt_datafile.FtMgmtDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snhead_swarp','MISCFILE','head file','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sntar_stamps','MISCFILE','gzipped tar file generated after makestamps','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('psfex_starlist','IMAGE','List of stars that were picked to construct PSF','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_norm_dflatcor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_bkg_immask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_streak','CATALOG',NULL,'filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_satstar','CATALOG',NULL,'filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_head_scamp_full','MISCFILE','exposure-based head file output by astrorefine step in multiepoch pipeline','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_head_scamp','MISCFILE','ccd-based head file created by splitting coadd_head_scamp_full','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_qa_scamp','MISCFILE','QA files from coadd astrorefine','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_xml_scamp','MISCFILE','XML file from coadd astrorefine','filemgmt.ftmgmt_coadd_xml_scamp.FtMgmtCoaddXmlScamp');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_msk','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_tmpsci','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_tmpsci','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_cat_psfex_starlist','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_xml_scamp_2','DESFILE','Never use with register_files.py.   Only for datafile ingest into 2nd QA table.','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_msk','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_sci','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_wgt','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_sci','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_wgt','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_nwgint','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_psfex_model','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_psfex_model','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_segmap','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_cat','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det_psfcat','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_segmap','MISCFILE','Segmentation map for a coadd','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_cat_scamp_full','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_cat_psfex_starlist','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd','COADD',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_psfcat','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snsci_distmpl','IMAGE','science portion of a distorted SNe template','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('junk_tar','DESFILE','tar of unregistered files from a job','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_lintable','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_illumcor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_fringecor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('psmfit','PSMFIT','table holding a psm solution',NULL);
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snwgt_distmpl','IMAGE','weight portion of a distorted SNe template','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snsci_fakediff','IMAGE','science portion of a fake difference','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snmask_fakediff','IMAGE','mask portion of a fake difference','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snwgt_fakediff','IMAGE','wgt portion of a fake difference','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snkern_fakediff','IMAGE','kernel fake difference','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snlist_filterobj','DESFILE','list of objects output by filterobj','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_fakediff','DESFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('qa_assess','MISCFILE','QA outputs of firstcut assess','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred','IMAGE','SN reduced image','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snsci_red','DESFILE','Science hdu of image','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snmask_red','DESFILE','Mask hdu of image','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snxtalked_sci','IMAGE','SN crosstalk corrected image','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_satstars','CATALOG','SN','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_scamp','CATALOG','SN','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_scamp_full','CATALOG','SN','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_trailbox','CATALOG','SN','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snhead_scamp_full','MISCFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snbkg_red','IMAGE','SN','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snstreaks_red','DESFILE','SN','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_psfex','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snlist_fakeobj','DESFILE','list of objects output by doFake','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snpsfex_model','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snxml_psfex','MISCFILE',NULL,'filemgmt.ftmgmt_datafile.FtMgmtDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snrefcat','DESFILE','reference catalog','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snsci_tmpl','SNTEMPLATE','image portion of a SNe template',NULL);
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snwgt_tmpl','SNTEMPLATE','weight portion of a SNe template',NULL);
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_tmpl','SNTEMPLATE','sex catalog portion of a SNe template',NULL);
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_dflatref','CALIBRATION','binned focal plane template used in skycompare','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mini_dflatcor','MISCFILE','binned version of mdflatcor cal_dflatcor files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mini_norm_dflatcor','MISCFILE','binned version of norm dflatcor files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_cat','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_det','COADD',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_molys','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_hpix','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_tile','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_toly','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_skypca_binned_fp','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_skypca_tmpl','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_psfex_starlist','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('pixcor_mini_red','MISCFILE','Binned image of red file','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('pixcor_red_binned_fp','MISCFILE','Focal plane of binned pixcor files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('dflatcor_binned_fp','MISCFILE','binned focal plane combined from pixcor_mini_dflat files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('bleedmask_mini','MISCFILE','Binned images of red_bleedmasked files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('bleedmask_binned_fp','MISCFILE','Focal plane of binned bleedmasked files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snlist_starcat','DESFILE','list output by makeStarCat','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snmltrain','DESFILE','SNe machine learning training dataset, e.g. used by autoscan','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_pixcor_nullwgt','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_immask_nullwgt','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_xml_psfex','MISCFILE',NULL,'filemgmt.ftmgmt_datafile.FtMgmtDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('pixcor_dflat','CALIBRATION','dflat image corrected for input to mkflatcor','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('pixcor_mini_dflat','MISCFILE','binned version of pixcor_dflat','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('immask_mini','MISCFILE','Binned images of red_immasked files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_immask','IMAGE','SN reduced image - product of immask','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('immask_binned_fp','MISCFILE','Focal plane of binned immask files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('compare_dflat_binned_fp','MISCFILE',NULL,'filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_detrend','IMAGE','SN reduced image - product of imcorrect','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_wcs','IMAGE','SN reduced image - product of scampUpdateHead()','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_mkbleedmask','IMAGE','SN reduced image - product of mkbleedmask','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_detrend','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_wcs','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_mkbleedmask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_immask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_pixcor','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_starflat','IMAGE','Starflat corrected red','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_immask_rowinterp','IMAGE','Result for row_interp of pixcorrect module using immask as input','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_bkg_nullwgt','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_skysub','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_bf','CALIBRATION','Brighter-fatter calibration file for use in SE','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('pixcor_dflat_binned_fp','MISCFILE','binned focal plane combined from pixcor_mini_dflat files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('norm_dflatcor_binned_fp','MISCFILE','binned focal plane combined from pixcor_mini_dflat files','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_starflat','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('skyfit_binned_fp','MISCFILE','Binned focal plane product of skyfit','filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snmanifest','DESFILE','manifest containing SNe exposures','filemgmt.ftmgmt_snmanifest.FtMgmtSNManifest');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('wcl','DESFILE','wcl file used in processing','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('log','DESFILE','stdout/stderr from running a wrapper','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_finalcut','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_psfex','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_firstcut','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_scamp_full','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_trailbox','CATALOG',NULL,'filemgmt.ftmgmt_fitsdatafile.FtMgmtFitsDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('head_scamp','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('head_scamp_full','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('psfex_model','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('xml_psfex','MISCFILE',NULL,'filemgmt.ftmgmt_datafile.FtMgmtDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('xml_scamp','MISCFILE',NULL,'filemgmt.ftmgmt_datafile.FtMgmtDatafile');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('xtalked_sci','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cat_scamp','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('config','DESFILE','configuration files for software run inside pipelines','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('xtalked_bias','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('xtalked_dflat','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('qa_scamp','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_qa','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_polygons','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('red_bkg','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('raw','EXPOSURE',NULL,'filemgmt.ftmgmt_raw.FtMgmtRaw');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_biascor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_dflatcor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_bpm','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_photflatcor','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('cal_pupil','CALIBRATION',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_pixcor_nullwgt','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snbleedmask_binned_fp','MISCFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snbleedmask_mini','MISCFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_streak','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snskyfit_binned_fp','MISCFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_bkg_immask','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_csv_ccdgon','MISCFILE','csv for ingestion into ccdgon table','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_csv_cobjmoly','MISCFILE','csv for ingestion into coadd_object_molygon table','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_csv_molyccd','MISCFILE','csv for ingestion into molygon_ccdgon table','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_csv_molygon','MISCFILE','csv for ingestion into molygon table','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_wavg','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_wavg_oclink','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_extinct_ebv','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_extinct_band','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_tiff','MISCFILE','Pseudo Color tiff of coadded image for DES tile','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_ptif','MISCFILE','PTIF file for DES tile','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('sncat_satstar','CATALOG',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_skysub','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_starflat','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_bkg_nullwgt','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_meds','MISCFILE','Science output of MEDS','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_meds_yaml','DESFILE','yaml for MEDS','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('snred_pixcor','IMAGE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_meds_objmap','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_mof_nbrs','MISCFILE','Fits list created for MOF step','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_mof_fof','MISCFILE','Fits list created for MOF step','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_mof_chunk','MISCFILE','Fits subset created for MOF step','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_shear','MISCFILE','shear output from ngmix','filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('mangle_systematics','MISCFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_msk_nobkg','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_nobkg','COADD',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_ptif_nobkg','MISCFILE','PTIF file for DES tile','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_sci_nobkg','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_tiff_nobkg','MISCFILE','Pseudo Color tiff of coadded image for DES tile','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_wgt_nobkg','DESFILE',NULL,'filemgmt.ftmgmt_genfits.FtMgmtGenFits');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_tmpsci_nobkg','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('coadd_qa_psfex','MISCFILE','QA files from coadd astrorefine','filemgmt.ftmgmt_generic.FtMgmtGeneric');
INSERT INTO OPS_FILETYPE (FILETYPE,METADATA_TABLE,DESCRIPTION,FILETYPE_MGMT) VALUES ('medslist','DESFILE',NULL,'filemgmt.ftmgmt_generic.FtMgmtGeneric');
;
