CREATE TABLE "OPS_DATA_STATE_DEF" (
"STATE" TEXT,
PRIMARY KEY ("STATE"));
INSERT INTO OPS_DATA_STATE_DEF (STATE) VALUES ('ACTIVE');
INSERT INTO OPS_DATA_STATE_DEF (STATE) VALUES ('ARCHIVED');
INSERT INTO OPS_DATA_STATE_DEF (STATE) VALUES ('JUNK');
INSERT INTO OPS_DATA_STATE_DEF (STATE) VALUES ('NEW');
