CREATE TABLE "PFW_BLOCK" (
"BLKNUM" INTEGER NOT NULL,
"NAME" TEXT NOT NULL,
"CONDORID" INTEGER,
"MODULELIST" TEXT NOT NULL,
"NUMEXPJOBS" INTEGER,
"TARGET_SITE" TEXT,
"TASK_ID" INTEGER NOT NULL,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
PRIMARY KEY ("TASK_ID"));
