CREATE TABLE "PFW_DATA_QUERY" (
"MODNAME" TEXT NOT NULL,
"DATATYPE" TEXT NOT NULL,
"DATANAME" TEXT,
"EXECNAME" TEXT NOT NULL,
"CMDARGS" TEXT,
"VERSION" TEXT,
"TASK_ID" INTEGER NOT NULL,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
"PFW_BLOCK_TASK_ID" INTEGER NOT NULL
);
