CREATE TABLE "PFW_WRAPPER" (
"WRAPNUM" INTEGER NOT NULL,
"NAME" TEXT NOT NULL,
"INPUTWCL" TEXT,
"OUTPUTWCL" TEXT,
"LOG" TEXT,
"MODNAME" TEXT NOT NULL,
"TASK_ID" INTEGER NOT NULL,
"DISKUSAGE" INTEGER,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
"WRAPKEYS" TEXT,
"PFW_BLOCK_TASK_ID" INTEGER NOT NULL,
"PFW_JOB_TASK_ID" INTEGER NOT NULL,
PRIMARY KEY ("TASK_ID"));
