CREATE TABLE "PFW_REQUEST" (
"REQNUM" INTEGER NOT NULL,
"PROJECT" TEXT NOT NULL,
"JIRA_ID" TEXT NOT NULL,
"PIPELINE" TEXT NOT NULL,
"USER_CREATED_BY" TEXT DEFAULT 'USER' NOT NULL,
"MODULE_CREATED_BY" TEXT DEFAULT 'USER' NOT NULL,
"CREATED_DATE" TIMESTAMP (6) DEFAULT 1234567890. NOT NULL,
"CAMPAIGN" TEXT,
PRIMARY KEY ("REQNUM"));
