CREATE TABLE "PROCTAG" (
"TAG" TEXT NOT NULL,
"CREATED_DATE" TIMESTAMP (6) DEFAULT 123456 NOT NULL,
"CREATED_BY" TEXT DEFAULT 'USER' NOT NULL,
"PFW_ATTEMPT_ID" INTEGER,
PRIMARY KEY ("TAG", "PFW_ATTEMPT_ID"));
