CREATE TABLE "SEMINFO" (
"ID" INTEGER NOT NULL,
"NAME" TEXT NOT NULL,
"SLOT" INTEGER,
"REQUEST_TIME" TIMESTAMP (6),
"GRANT_TIME" TIMESTAMP (6),
"RELEASE_TIME" TIMESTAMP (6),
"NUM_SLOTS" INTEGER,
"NUM_REQUESTS" INTEGER,
"TASK_ID" INTEGER
);
