CREATE TABLE "SEMLOCK" (
"NAME" TEXT NOT NULL,
"SLOT" INTEGER NOT NULL,
"IN_USE" INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY ("NAME", "SLOT"));

INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-in', 0);
INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-in', 1);
INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-in', 2);
INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-out', 0);
INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-out', 1);
INSERT INTO SEMLOCK (NAME, SLOT) VALUES ('mock-out', 2);