CREATE TABLE "TASK_MESSAGE" (
"TASK_ID" INTEGER DEFAULT 0,
"PFW_ATTEMPT_ID" INTEGER NOT NULL,
"MESSAGE_TIME" TIMESTAMP (6) NOT NULL,
"MESSAGE_LVL" INTEGER NOT NULL,
"OPS_MESSAGE_PATTERN_ID" INTEGER NOT NULL,
"MESSAGE" TEXT NOT NULL,
"LOG_FILE" TEXT NOT NULL,
"LOG_LINE" INTEGER DEFAULT 0 NOT NULL
);
