CREATE TABLE "TRANSFER_BATCH" (
"TASK_ID" INTEGER NOT NULL,
"PARENT_TASK_ID" INTEGER NOT NULL,
"SRC" TEXT,
"DST" TEXT,
"TOTAL_NUM_BYTES" INTEGER,
"TOTAL_NUM_FILES" INTEGER,
"TRANSFER_CLASS" TEXT,
PRIMARY KEY ("TASK_ID"));
