 CREATE TABLE "WAVG" (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "BAND" TEXT NOT NULL,
    "WAVG_MAG_PSF" FLOAT NOT NULL,
    "WAVG_MAGERR_PSF" FLOAT NOT NULL,
    "WAVG_MAGRMS_PSF" FLOAT NOT NULL,
    "WAVG_SPREAD_MODEL" FLOAT NOT NULL,
    "WAVG_SPREADERR_MODEL" FLOAT NOT NULL,
    "NEPOCHS" INTEGER NOT NULL,
    "DUP" INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY ("COADD_OBJECT_ID", "FILENAME"));
