CREATE TABLE "WAVG_OCLINK" (
    "COADD_OBJECT_ID" INTEGER NOT NULL,
    "FILENAME" TEXT NOT NULL,
    "BAND" TEXT NOT NULL,
    "COADD_OBJECT_FILENAME" TEXT NOT NULL,
    "SE_OBJECT_FILENAME" TEXT NOT NULL,
    "SE_OBJECT_NUMBER" INTEGER NOT NULL,
    "DUP" INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY ("COADD_OBJECT_ID", "COADD_OBJECT_FILENAME", "SE_OBJECT_FILENAME", "SE_OBJECT_NUMBER"));
