CREATE TABLE "ZEROPOINT" (
"IMAGENAME" TEXT NOT NULL,
"SOURCE" TEXT NOT NULL,
"VERSION" TEXT,
"CATALOGNAME" TEXT NOT NULL,
"EXPNUM" INTEGER NOT NULL,
"CCDNUM" INTEGER NOT NULL,
"BAND" TEXT NOT NULL,
"INSERT_DATE" DATE,
"MAG_ZERO" REAL NOT NULL,
"SIGMA_MAG_ZERO" REAL,
"MAG_ONE" REAL,
"SIGMA_MAG_ONE" REAL,
"TAG" TEXT,
"FLAG" INTEGER,
PRIMARY KEY("CATALOGNAME", "SOURCE", "VERSION"));

